### ISSUE TITLE
address already in use :::80

### ISSUE THREAD

**Issue by hoverlord** [Czino/ring-of-fire-sharing#8]
hi! i´m on mac os and trying to launch the dashboard gui. i think it tries running the server on port 80, where my apache is  running already. in config.js i left the line "url: 'https://localhost:8080'" intact so i assume it should try to start the server on port 8080, not on port 80?

```
% npm run server

> ring-of-fire-server@0.0.1 server
> node index.js

Created http server with port 80
node:events:346
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::80
    at Server.setupListenHandle [as _listen2] (node:net:1311:16)
    at listenInCluster (node:net:1359:12)
    at Server.listen (node:net:1446:7)
    at Object.<anonymous> (/Library/WebServer/Documents/ring-of-fire-sharing-gui/gui/server.js:331:24)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Library/WebServer/Documents/ring-of-fire-sharing-gui/gui/index.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1338:8)
    at processTicksAndRejections (node:internal/process/task_queues:81:21) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 80
}
```

**Comment by Czino** [comment]
I just pushed a fix that allows you to configure a different port in the config.js

Just be sure to access the GUI in the browser with the given port (e.g. http://localhost:3080/

**Comment by hoverlord** [comment]
This is working, thanks a lot! 👌
